# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
coreutils = {}
extrautils = {}
ion = {}
netutils = {}
pkgutils = {}
tar = {}
userutils = {}

[[files]]
path = "/etc/net/dns"
data = "208.67.222.222"

[[files]]
path = "/etc/net/ip"
data = "10.0.2.15"

[[files]]
path = "/etc/net/ip_router"
data = "10.0.2.2"

[[files]]
path = "/etc/net/ip_subnet"
data = "255.255.255.0"

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"

# User settings
[users.root]
# Password is set to "password"
password = "$argon2i$m=4096,t=10,p=1$Tnc4UVV0N00$ML9LIOujd3nmAfkAwEcSTMPqakWUF0OUiLWrIy0nGLk"
uid = 0
gid = 0
name = "root"
home = "/root"
