[[drivers]]
name = "82543GC NIC"
class = 2
vendor = 32902
device = 4100
command = ["/sbin/e1000d", "$NAME", "$BAR0", "$IRQ"]

[[drivers]]
name = "82540EM NIC"
class = 2
vendor = 32902
device = 4110
command = ["/sbin/e1000d", "$NAME", "$BAR0", "$IRQ"]

[[drivers]]
name = "82545EM NIC"
class = 2
vendor = 32902
device = 4111
command = ["/sbin/e1000d", "$NAME", "$BAR0", "$IRQ"]

[[drivers]]
name = "RTL8168 NIC"
class = 2
vendor = 4332
device = 33128
command = ["/sbin/rtl8168d", "$NAME", "$BAR2", "$IRQ"]

[[drivers]]
name = "XHCI"
class = 12
subclass = 3
interface = 48
command = ["/sbin/xhcid", "$NAME", "$BAR0", "$IRQ"]
