[package]
name = "tcpd"
version = "0.1.0"

[dependencies]
netutils = { git = "https://github.com/redox-os/netutils.git" }
rand = "0.3"
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = { git = "https://github.com/redox-os/syscall.git" }
